version: '3.8'

services:
  # Service for the vulnerable web application
  web-vulnerable:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./vulnerable-app:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - csrf-lab
    hostname: web-vulnerable

  # Service for the attacker's site
  attacker-site:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./attacker-site:/usr/share/nginx/html
    networks:
      - csrf-lab

  # Service for the database
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: csrflabroot
      MYSQL_DATABASE: vulnerable_app
      MYSQL_USER: csrfuser
      MYSQL_PASSWORD: csrfpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - csrf-lab

networks:
  csrf-lab:
    driver: bridge

volumes:
  db-data: