version: '3.8'

services:
  vulnerable_app:
    build: ./vulnerable_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  malicious_site:
    build: ./malicious_site
    ports:
      - "808:80"
